[package]
name = "addin-zeromq"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
addin1c = "0.4"
zmq = "0.10"
smallvec = "*"

[patch.crates-io]
"zmq-sys" = { path = 'zmq-sys' }
